const List<String> SCROLL_FACTS = [
  "Sun AKA the Helium Giant and the Earth's favourite star.",
  "The sun's gravity keeps all the other planets in the solar system in orbit, definitely a suitable job for the 'star' of the solar system.",
  "Other than being a poisonous liquid metal in thermometers, Mercury is also the smallest planet in our solar system.",
  "Sadly, it can't keep a single moon in orbit due to its weak gravitational pull.",
  "Venus is the hottest planet around, no wonder it's the only one named after a woman.",
  "A day on Venus is as long as a year on Earth.",
  "Don't think of a ball when you think of the Earth, try imagining a mutated egg.",
  "Pollution extends to space too… thousands of satellites litter the atmosphere.",
  "The moon has been slowly pulling away from the Earth, but who wouldn't be tired after 4.5 billion years?",
  "Mars is known for it's deadly dust storms… make sure to pack some tissues for your visit!",
  "The best place to compete in the high jump is on Mars, as you can jump much higher due to it's weak gravity.",
  "You can see Mars from Earth, without a telescope or even binoculars.",
  "As Jupiter this is a gas giant, no spaceship would be able to land on the surface.",
  "Home to the longest running storm in the area(The Great Red Spot)… one that's even bigger than Earth.",
  "Say goodbye to the largest planet in our solar system.",
  "If you were to drop the gas giant, Saturn, into a huge body of water, it would float…",
  "Saturn's largest moon Titan, is larger than Mercury, and is a candidate for potential life.",
  "It's liquid ice rings are slowly deteriorating.",
  "Retrograde rotation: This is the only planet to rotate on its side, east to west, just like Venus.",
  "Uranus is twin to Neptune just as Venus is to Earth.",
  "It has 28 known moons!",
  "One year here is equivalent to 165 Earth years.",
  "The Kuiper Belt is filled with icy debris, comets and exoplanets. Much of this is thought to be 'leftovers' from the solar system's early days.",
  "It's largest moon is Triton and it is believed to be stolen from the Kuiper Belt.",
  "Neptune is four times wider than Earth!",//Neptune
  "It has rings too!",
  "Its largest moon is Triton and it is believed to be stolen from the Kuiper Belt.",
  "Named after the Roman god of the sea. Its blue hue stems from absorbing methane gas.",
  "One year is equivalent to 165 Earth years.",
  
];
